script<-sub("^--file=","",commandArgs()[grepl("^--file=",commandArgs())][1]);root<-dirname(dirname(normalizePath(script)))
source(file.path(root,"skills/scientific-plotting/scripts/plot_cli.R"))
out<-tempfile("recipe-tests-");dir.create(out)
fails<-function(expr)inherits(tryCatch({force(expr);NULL},error=identity),"error")
for(kind in names(.recipe_catalog)) {
  config<-yaml::read_yaml(file.path(root,"examples/configs",paste0(kind,".yml")))
  panel<-config$panels[[1]]
  data<-load_scientific_table(file.path(root,"examples/configs",panel$data))
  recipe<-draw_scientific_recipe(kind,data,"nature",.sp_or(panel$options,list()))
  paths<-export_scientific(recipe$plot,file.path(out,kind),formats=c("png","svg"),width_mm=150,height_mm=110,dpi=90,metadata=recipe$report)
  stopifnot(all(file.exists(paths)),recipe$report$n_rows==nrow(data))
}
metrics<-classification_scientific_metrics(data.frame(truth=c(0,0,1,1),score=c(.1,.4,.35,.8)))
stopifnot(abs(metrics$auroc-.75)<1e-12,abs(metrics$average_precision-5/6)<1e-12)
tied<-classification_scientific_metrics(data.frame(truth=c(0,0,1,1),score=rep(.5,4)))
stopifnot(tied$auroc==.5,tied$average_precision==.5)
stopifnot(fails(classification_scientific_metrics(data.frame(truth=c(0,0),score=c(.2,.3)))))
paired<-read.csv(file.path(root,"skills/scientific-plotting/assets/templates/paired.csv"))
options<-list(contrasts=list(c("A","B")),method="paired-t",experimental_unit="subject")
stats<-do.call(compare_scientific_groups,c(list(data=paired),options))
shuffled<-do.call(compare_scientific_groups,c(list(data=paired[rev(seq_len(nrow(paired))),]),options))
stopifnot(stats$n_first==12,abs(stats$effect-shuffled$effect)<1e-12,stats$ci_low<stats$effect,stats$effect<stats$ci_high)
stopifnot(fails(do.call(compare_scientific_groups,c(list(data=paired[-1,]),options))))
stopifnot(fails(do.call(compare_scientific_groups,c(list(data=paired),modifyList(options,list(method="welch-t"))))))
config<-yaml::read_yaml(file.path(root,"examples/configs/excel.yml"))
panel<-config$panels[[1]]
excel<-load_scientific_table(file.path(root,"examples/configs",panel$data),sheet=panel$sheet,reshape=panel$reshape)
stopifnot(nrow(excel)==24,all(c("subject","group","value") %in% names(excel)))
config$presets<-list("nature");config$formats<-list("png","svg");config$panels[[1]]$data<-normalizePath(file.path(root,"examples/configs",panel$data))
path<-file.path(out,"job.yml");yaml::write_yaml(config,path)
run_scientific_config(path,output=file.path(out,"batch"))
stopifnot(file.exists(file.path(out,"batch-nature.statistics.csv")),fails(run_scientific_config(path,output=file.path(out,"batch"))))
before<-read.csv(file.path(out,"batch-nature.statistics.csv"))
status<-system2(file.path(R.home("bin"),"Rscript"),c(shQuote(file.path(out,"batch-nature.source.R")),shQuote(file.path(root,"skills/scientific-plotting/scripts"))),stdout=FALSE)
stopifnot(status==0,isTRUE(all.equal(before,read.csv(file.path(out,"batch-nature.statistics.csv")))))
config$presets<-list("nature","invalid");yaml::write_yaml(config,path)
stopifnot(fails(run_scientific_config(path,output=file.path(out,"failed"))),!length(list.files(out,pattern="^failed")))
# Rendered QA detects literal low-contrast text and flags a raster export below 300 DPI.
p<-ggplot2::ggplot(data.frame(x=1,y=1),ggplot2::aes(x,y))+ggplot2::geom_text(label="Yellow",colour="yellow")+scientific_theme("nature")
paths<-export_scientific(p,file.path(out,"qa"),formats=c("svg","png"),dpi=100)
qa<-inspect_scientific_svg(paths[["svg"]]);codes<-vapply(qa$findings,function(f)f$code,character(1))
stopifnot("low-text-contrast" %in% codes,length(inspect_scientific_exports(paths,89,64,100)$findings)>0)
source(file.path(root,"skills/scientific-plotting/scripts/specialized_adapters.R"))
if(requireNamespace("ggraph",quietly=TRUE)) {
  network<-read.csv(file.path(root,"skills/scientific-plotting/assets/templates/network.csv"))
  plot<-ggraph_scientific_network(network)
  export_scientific(plot,file.path(out,"ggraph"),formats="png",width_mm=120,height_mm=100,dpi=100)
}
if(requireNamespace("ComplexHeatmap",quietly=TRUE)) {
  matrix<-read.csv(file.path(root,"skills/scientific-plotting/assets/templates/heatmap.csv"))
  plot<-complex_scientific_heatmap(matrix,center=0)
  export_scientific(plot,file.path(out,"complex"),formats=c("pdf","svg","png"),width_mm=150,height_mm=110,dpi=100)
}
unlink(out,recursive=TRUE)
cat("R expanded checks passed: 22 recipes, statistics, metrics/ties, Excel, batch failure/collisions, QA and installed domain adapters\n")
